[project]
name = "6-langchain-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cll", email = "582233293@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.3.17",
]

[project.scripts]
6-langchain-exercise = "6_langchain_exercise:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
